title: My Portfolio
description: My projects and work
theme: minima

sass:
  style: compressed

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

collections:
  projects:
    output: true
    permalink: /projects/:name/

minima:
  skin: classic